<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Every</name>
   <tag></tag>
   <elementGuidId>4569bd21-ab2b-4026-9ad2-c41b64c06a53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;elimForm&quot;]/fieldset/table/tbody/tr[11]/td[2]/table/tbody/tr[3]/td[2]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;elimForm&quot;]/fieldset/table/tbody/tr[11]/td[2]/table/tbody/tr[3]/td[2]/div/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
