<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Other</name>
   <tag></tag>
   <elementGuidId>41b0060c-54f6-4a1e-a892-b64d1f1e6780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;careForm&quot;]/div/fieldset/table/tbody/tr[71]/td[2]/table/tbody/tr[2]/td/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;careForm&quot;]/div/fieldset/table/tbody/tr[71]/td[2]/table/tbody/tr[2]/td/div/textarea</value>
   </webElementProperties>
</WebElementEntity>
