<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Patients_Goals</name>
   <tag></tag>
   <elementGuidId>15f93865-53bb-4fff-b980-11463370c725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;careForm&quot;]/div/fieldset/table/tbody/tr[71]/td[2]/table/tbody/tr[4]/td/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;careForm&quot;]/div/fieldset/table/tbody/tr[71]/td[2]/table/tbody/tr[4]/td/div/textarea</value>
   </webElementProperties>
</WebElementEntity>
