<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chb_Mental_Cognitive</name>
   <tag></tag>
   <elementGuidId>e2e6c014-ef82-45ba-b877-0f4b5ee676d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;neuroForm&quot;]/div/fieldset/table/tbody/tr[17]/td[2]/table/tbody/tr[2]/td[1]/div/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;neuroForm&quot;]/div/fieldset/table/tbody/tr[17]/td[2]/table/tbody/tr[2]/td[1]/div/label/input</value>
   </webElementProperties>
</WebElementEntity>
