<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Able_to_move</name>
   <tag></tag>
   <elementGuidId>557fa73c-0d52-4051-86ca-320923e84c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;adlForm&quot;]/fieldset/table/tbody/tr[3]/td[2]/table/tbody/tr[4]/td[2]/table/tbody/tr[1]/td/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;adlForm&quot;]/fieldset/table/tbody/tr[3]/td[2]/table/tbody/tr[4]/td[2]/table/tbody/tr[1]/td/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
