<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Phone</name>
   <tag></tag>
   <elementGuidId>e622eb63-97b9-45fb-9c54-f847e54adadc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;neuroForm&quot;]/div/fieldset/table/tbody/tr[15]/td[2]/table/tbody/tr[2]/td[2]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;neuroForm&quot;]/div/fieldset/table/tbody/tr[15]/td[2]/table/tbody/tr[2]/td[2]/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
