<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Sign_language(Type)</name>
   <tag></tag>
   <elementGuidId>3960c013-cdba-44f8-9f73-ad82c219c0c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;neuroForm&quot;]/div/fieldset/table/tbody/tr[15]/td[2]/table/tbody/tr[3]/td/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;neuroForm&quot;]/div/fieldset/table/tbody/tr[15]/td[2]/table/tbody/tr[3]/td/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
