<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Other</name>
   <tag></tag>
   <elementGuidId>3c0d600e-587c-470d-a5fb-350d9054f815</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;elimForm&quot;]/fieldset/table/tbody/tr[2]/td[2]/table/tbody/tr[2]/td[2]/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;elimForm&quot;]/fieldset/table/tbody/tr[2]/td[2]/table/tbody/tr[2]/td[2]/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
