<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_WNL</name>
   <tag></tag>
   <elementGuidId>4ce7cb31-a05f-4860-8088-289f2230d055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;medicationForm&quot;]/fieldset/table/tbody/tr[19]/td/table/tbody/tr[8]/td/div[2]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;medicationForm&quot;]/fieldset/table/tbody/tr[19]/td/table/tbody/tr[8]/td/div[2]/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
