<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chb_NA</name>
   <tag></tag>
   <elementGuidId>827c8737-dfe2-4b58-80f6-d841dc74b0aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;careForm&quot;]/div/fieldset/table/tbody/tr[12]/td[2]/table/tbody/tr/td/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;careForm&quot;]/div/fieldset/table/tbody/tr[12]/td[2]/table/tbody/tr/td/div/div/div/label</value>
   </webElementProperties>
</WebElementEntity>
