<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chb_Lower_extremity_Fine</name>
   <tag></tag>
   <elementGuidId>04e985b6-2068-4dc1-a6cb-6009171c53fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section/section/data/section/div[2]/div/div/div/div/div/div/div/fieldset/div[2]/div/div[4]/div/div[2]/div/form/div/fieldset/table/tbody/tr[10]/td[2]/table/tbody/tr/td[2]/table/tbody/tr[2]/td[3]/div/label[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/section/data/section/div[2]/div/div/div/div/div/div/div/fieldset/div[2]/div/div[4]/div/div[2]/div/form/div/fieldset/table/tbody/tr[10]/td[2]/table/tbody/tr/td[2]/table/tbody/tr[2]/td[3]/div/label[1]/input</value>
   </webElementProperties>
</WebElementEntity>
