<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_IV_pump_Brand_Model</name>
   <tag></tag>
   <elementGuidId>50b7cc07-6e0c-40bf-abd2-adeb4efe0fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;medicationForm&quot;]/fieldset/table/tbody/tr[23]/td/table/tbody/tr[3]/td/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>//*[@id=&quot;medicationForm&quot;]/fieldset/table/tbody/tr[23]/td/table/tbody/tr[3]/td/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
