<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Flush_solution</name>
   <tag></tag>
   <elementGuidId>9fa26273-7e67-491d-9204-d1fc7a13e7f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;medicationForm&quot;]/fieldset/table/tbody/tr[15]/td/table/tbody/tr[8]/td/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;medicationForm&quot;]/fieldset/table/tbody/tr[15]/td/table/tbody/tr[8]/td/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
