<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chb_1</name>
   <tag></tag>
   <elementGuidId>57bea9b0-3655-4903-81af-c14db1974840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;M2102_CARE_TYPE_SRC_SPRVSN&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;M2102_CARE_TYPE_SRC_SPRVSN&quot;]</value>
   </webElementProperties>
</WebElementEntity>
