<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_times_a_day</name>
   <tag></tag>
   <elementGuidId>5c2c868e-fdc6-4b52-bbdd-d9f0f12a0fb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;elimForm&quot;]/fieldset/table/tbody/tr[39]/td[2]/table/tbody/tr/td[2]/table/tbody/tr[6]/td/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;elimForm&quot;]/fieldset/table/tbody/tr[39]/td[2]/table/tbody/tr/td[2]/table/tbody/tr[6]/td/div/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
