<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chb_1_-_Yes</name>
   <tag></tag>
   <elementGuidId>837fe0bd-be0c-4d14-a4be-e5c0d02a088d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;medicationForm&quot;]/fieldset/table/tbody/tr[4]/td[2]/fieldset/table/tbody/tr/td/div[2]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;medicationForm&quot;]/fieldset/table/tbody/tr[4]/td[2]/fieldset/table/tbody/tr/td/div[2]/label/input</value>
   </webElementProperties>
</WebElementEntity>
