<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Dressing_change_frequency</name>
   <tag></tag>
   <elementGuidId>fa243d71-bc40-4456-84e7-c9afd26d350e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;elimForm&quot;]/fieldset/table/tbody/tr[17]/td[2]/table/tbody/tr[2]/td[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;elimForm&quot;]/fieldset/table/tbody/tr[17]/td[2]/table/tbody/tr[2]/td[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
