<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Frequency</name>
   <tag></tag>
   <elementGuidId>ddf3e5e9-0914-4dd5-9ac6-e8d3645ada3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;elimForm&quot;]/fieldset/table/tbody/tr[13]/td[2]/table/tbody/tr[3]/td[2]/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;elimForm&quot;]/fieldset/table/tbody/tr[13]/td[2]/table/tbody/tr[3]/td[2]/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
