<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chb_No</name>
   <tag></tag>
   <elementGuidId>b94ab03d-a26b-4524-a15f-b2f9994e239c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SOOELIMINATION0165</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SOOELIMINATION0165</value>
   </webElementProperties>
</WebElementEntity>
