<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Loss_of_ability_to_move_a_body_part</name>
   <tag></tag>
   <elementGuidId>725c7442-5bf7-4e15-82c9-a33648958f8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;neuroForm&quot;]/div/fieldset/table/tbody/tr[11]/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td[2]/div[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;neuroForm&quot;]/div/fieldset/table/tbody/tr[11]/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td[2]/div[4]/input</value>
   </webElementProperties>
</WebElementEntity>
