<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt__Other</name>
   <tag></tag>
   <elementGuidId>01ca4757-6bec-456c-b650-9f4a88a9eda7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;careForm&quot;]/div/fieldset/table/tbody/tr[64]/td[2]/table/tbody/tr/td[2]/div[9]/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;careForm&quot;]/div/fieldset/table/tbody/tr[64]/td[2]/table/tbody/tr/td[2]/div[9]/div[2]/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
