<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt___Other</name>
   <tag></tag>
   <elementGuidId>22c6fd97-eaab-463e-9f7f-65140f74444a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;careForm&quot;]/div/fieldset/table/tbody/tr[64]/td[2]/table/tbody/tr/td[2]/div[10]/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;careForm&quot;]/div/fieldset/table/tbody/tr[64]/td[2]/table/tbody/tr/td[2]/div[10]/div[2]/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
