<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Tab12_ADLs_IADLs</name>
   <tag></tag>
   <elementGuidId>2cb626cb-033d-4ec5-b28e-f8a724d06c77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#adl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#adl</value>
   </webElementProperties>
</WebElementEntity>
