<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Dressing_change_frequency</name>
   <tag></tag>
   <elementGuidId>2b7b8c4c-9ac4-4851-abd2-5d922b3b0563</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;medicationForm&quot;]/fieldset/table/tbody/tr[19]/td/table/tbody/tr[7]/td/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;medicationForm&quot;]/fieldset/table/tbody/tr[19]/td/table/tbody/tr[7]/td/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
