<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Need_for_community_services</name>
   <tag></tag>
   <elementGuidId>2e10618a-cb14-45d2-9d04-058b5be3ce1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;careForm&quot;]/div/fieldset/table/tbody/tr[23]/td/table/tbody/tr[1]/td[2]/div[4]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;careForm&quot;]/div/fieldset/table/tbody/tr[23]/td/table/tbody/tr[1]/td[2]/div[4]/div/input</value>
   </webElementProperties>
</WebElementEntity>
